rpms:
  - clevis
  - clevis-dracut
  - clevis-udisks2
  - evolution
  - freeipa-client
  - libratbag-ratbagd
  - vim
  - vim-default-editor
  - zenity
flatpaks:
  - com.github.tchx84.Flatseal
  - im.riot.Riot
  - io.freetubeapp.FreeTube
  - org.freedesktop.Piper
  - org.gustavoperedo.FontDownloader
  - org.keepassxc.KeePassXC
  - org.libreoffice.LibreOffice
  - org.videolan.VLC
